/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{ 
    /// <summary>
    /// Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by JSON)
    /// </summary>
    [DataContract]
    public partial class AddAudienceToAudienceGroupRequest : IEquatable<AddAudienceToAudienceGroupRequest>
    {
        /// <summary>
        /// The audience ID.
        /// </summary>
        /// <value>The audience ID.</value>
        [DataMember(Name="audienceGroupId", EmitDefaultValue=true)]
        public long AudienceGroupId { get; set; }

        /// <summary>
        /// The audience&#39;s name.
        /// </summary>
        /// <value>The audience&#39;s name.</value>
        [DataMember(Name="uploadDescription", EmitDefaultValue=false)]
        public string UploadDescription { get; set; }

        /// <summary>
        /// An array of up to 10,000 user IDs or IFAs.
        /// </summary>
        /// <value>An array of up to 10,000 user IDs or IFAs.</value>
        [DataMember(Name="audiences", EmitDefaultValue=false)]
        public List<Audience> Audiences { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddAudienceToAudienceGroupRequest {\n");
            sb.Append("  AudienceGroupId: ").Append(AudienceGroupId).Append("\n");
            sb.Append("  UploadDescription: ").Append(UploadDescription).Append("\n");
            sb.Append("  Audiences: ").Append(Audiences).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddAudienceToAudienceGroupRequest)obj);
        }

        /// <summary>
        /// Returns true if AddAudienceToAudienceGroupRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddAudienceToAudienceGroupRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddAudienceToAudienceGroupRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AudienceGroupId == other.AudienceGroupId ||
                    
                    AudienceGroupId.Equals(other.AudienceGroupId)
                ) && 
                (
                    UploadDescription == other.UploadDescription ||
                    UploadDescription != null &&
                    UploadDescription.Equals(other.UploadDescription)
                ) && 
                (
                    Audiences == other.Audiences ||
                    Audiences != null &&
                    other.Audiences != null &&
                    Audiences.SequenceEqual(other.Audiences)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + AudienceGroupId.GetHashCode();
                    if (UploadDescription != null)
                    hashCode = hashCode * 59 + UploadDescription.GetHashCode();
                    if (Audiences != null)
                    hashCode = hashCode * 59 + Audiences.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AddAudienceToAudienceGroupRequest left, AddAudienceToAudienceGroupRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddAudienceToAudienceGroupRequest left, AddAudienceToAudienceGroupRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
