/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// Gets or Sets AgeDemographic
    /// </summary>

    public enum AgeDemographic
    {
        /// <summary>
        /// Enum Age15Enum for age_15
        /// </summary>
        [EnumMember(Value = "age_15")]
        Age15Enum = 1,

        /// <summary>
        /// Enum Age20Enum for age_20
        /// </summary>
        [EnumMember(Value = "age_20")]
        Age20Enum = 2,

        /// <summary>
        /// Enum Age25Enum for age_25
        /// </summary>
        [EnumMember(Value = "age_25")]
        Age25Enum = 3,

        /// <summary>
        /// Enum Age30Enum for age_30
        /// </summary>
        [EnumMember(Value = "age_30")]
        Age30Enum = 4,

        /// <summary>
        /// Enum Age35Enum for age_35
        /// </summary>
        [EnumMember(Value = "age_35")]
        Age35Enum = 5,

        /// <summary>
        /// Enum Age40Enum for age_40
        /// </summary>
        [EnumMember(Value = "age_40")]
        Age40Enum = 6,

        /// <summary>
        /// Enum Age45Enum for age_45
        /// </summary>
        [EnumMember(Value = "age_45")]
        Age45Enum = 7,

        /// <summary>
        /// Enum Age50Enum for age_50
        /// </summary>
        [EnumMember(Value = "age_50")]
        Age50Enum = 8,

        /// <summary>
        /// Enum Age55Enum for age_55
        /// </summary>
        [EnumMember(Value = "age_55")]
        Age55Enum = 9,

        /// <summary>
        /// Enum Age60Enum for age_60
        /// </summary>
        [EnumMember(Value = "age_60")]
        Age60Enum = 10,

        /// <summary>
        /// Enum Age65Enum for age_65
        /// </summary>
        [EnumMember(Value = "age_65")]
        Age65Enum = 11,

        /// <summary>
        /// Enum Age70Enum for age_70
        /// </summary>
        [EnumMember(Value = "age_70")]
        Age70Enum = 12,
    }
}
