/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// Gets or Sets AppTypeDemographic
    /// </summary>

    public enum AppTypeDemographic
    {
        /// <summary>
        /// Enum IosEnum for ios
        /// </summary>
        [EnumMember(Value = "ios")]
        IosEnum = 1,

        /// <summary>
        /// Enum AndroidEnum for android
        /// </summary>
        [EnumMember(Value = "android")]
        AndroidEnum = 2,
    }
}
