/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AreaDemographicFilter : DemographicFilter, IEquatable<AreaDemographicFilter>
    {
        /// <summary>
        /// Gets or Sets OneOf
        /// </summary>
        [DataMember(Name="oneOf", EmitDefaultValue=false)]
        public List<AreaDemographic> OneOf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AreaDemographicFilter {\n");
            sb.Append("  OneOf: ").Append(OneOf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AreaDemographicFilter)obj);
        }

        /// <summary>
        /// Returns true if AreaDemographicFilter instances are equal
        /// </summary>
        /// <param name="other">Instance of AreaDemographicFilter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AreaDemographicFilter other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OneOf == other.OneOf ||
                    OneOf != null &&
                    other.OneOf != null &&
                    OneOf.SequenceEqual(other.OneOf)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OneOf != null)
                    hashCode = hashCode * 59 + OneOf.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AreaDemographicFilter left, AreaDemographicFilter right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AreaDemographicFilter left, AreaDemographicFilter right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
