/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// Failed type
    /// </summary>
    /// <value>Failed type</value>

    public enum AudienceGroupJobFailedType
    {
        /// <summary>
        /// Enum INTERNALERROREnum for INTERNAL_ERROR
        /// </summary>
        [EnumMember(Value = "INTERNAL_ERROR")]
        INTERNALERROREnum = 1,

        /// <summary>
        /// Enum AUDIENCEGROUPAUDIENCEINSUFFICIENTEnum for AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT
        /// </summary>
        [EnumMember(Value = "AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT")]
        AUDIENCEGROUPAUDIENCEINSUFFICIENTEnum = 2,
    }
}
