/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// An object representing a emoji substitution.
    /// </summary>
    [DataContract]
    public partial class EmojiSubstitutionObject
        : SubstitutionObject,
            IEquatable<EmojiSubstitutionObject>
    {
        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [Required]
        [DataMember(Name = "productId", EmitDefaultValue = false)]
        public string ProductId { get; set; }

        /// <summary>
        /// Gets or Sets EmojiId
        /// </summary>
        [Required]
        [DataMember(Name = "emojiId", EmitDefaultValue = false)]
        public string EmojiId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmojiSubstitutionObject {\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  EmojiId: ").Append(EmojiId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public new string ToJson()
        {
            var options = new JsonSerializerOptions { WriteIndented = true };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((EmojiSubstitutionObject)obj);
        }

        /// <summary>
        /// Returns true if EmojiSubstitutionObject instances are equal
        /// </summary>
        /// <param name="other">Instance of EmojiSubstitutionObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmojiSubstitutionObject other)
        {
            if (other is null)
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (
                    ProductId == other.ProductId
                    || ProductId != null && ProductId.Equals(other.ProductId)
                ) && (EmojiId == other.EmojiId || EmojiId != null && EmojiId.Equals(other.EmojiId));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (ProductId != null)
                    hashCode = hashCode * 59 + ProductId.GetHashCode();
                if (EmojiId != null)
                    hashCode = hashCode * 59 + EmojiId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(EmojiSubstitutionObject left, EmojiSubstitutionObject right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmojiSubstitutionObject left, EmojiSubstitutionObject right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
