/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// Channel state.
    /// </summary>
    /// <value>Channel state.</value>

    public enum EventMode
    {
        /// <summary>
        /// Enum ActiveEnum for active
        /// </summary>
        [EnumMember(Value = "active")]
        ActiveEnum = 1,

        /// <summary>
        /// Enum StandbyEnum for standby
        /// </summary>
        [EnumMember(Value = "standby")]
        StandbyEnum = 2,
    }
}
