/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class FlexButton : FlexComponent, IEquatable<FlexButton>
    {
        /// <summary>
        /// Gets or Sets Flex
        /// </summary>
        [DataMember(Name = "flex", EmitDefaultValue = true)]
        public int Flex { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name = "color", EmitDefaultValue = false)]
        public string Color { get; set; }

        /// <summary>
        /// Gets or Sets Style
        /// </summary>

        public enum StyleEnum
        {
            /// <summary>
            /// Enum PrimaryEnum for primary
            /// </summary>
            [EnumMember(Value = "primary")]
            PrimaryEnum = 1,

            /// <summary>
            /// Enum SecondaryEnum for secondary
            /// </summary>
            [EnumMember(Value = "secondary")]
            SecondaryEnum = 2,

            /// <summary>
            /// Enum LinkEnum for link
            /// </summary>
            [EnumMember(Value = "link")]
            LinkEnum = 3,
        }

        /// <summary>
        /// Gets or Sets Style
        /// </summary>
        [DataMember(Name = "style", EmitDefaultValue = true)]
        public StyleEnum Style { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [Required]
        [DataMember(Name = "action", EmitDefaultValue = false)]
        public Action Action { get; set; }

        /// <summary>
        /// Gets or Sets Gravity
        /// </summary>

        public enum GravityEnum
        {
            /// <summary>
            /// Enum TopEnum for top
            /// </summary>
            [EnumMember(Value = "top")]
            TopEnum = 1,

            /// <summary>
            /// Enum BottomEnum for bottom
            /// </summary>
            [EnumMember(Value = "bottom")]
            BottomEnum = 2,

            /// <summary>
            /// Enum CenterEnum for center
            /// </summary>
            [EnumMember(Value = "center")]
            CenterEnum = 3,
        }

        /// <summary>
        /// Gets or Sets Gravity
        /// </summary>
        [DataMember(Name = "gravity", EmitDefaultValue = true)]
        public GravityEnum Gravity { get; set; }

        /// <summary>
        /// Gets or Sets Margin
        /// </summary>
        [DataMember(Name = "margin", EmitDefaultValue = false)]
        public string Margin { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>

        public enum PositionEnum
        {
            /// <summary>
            /// Enum RelativeEnum for relative
            /// </summary>
            [EnumMember(Value = "relative")]
            RelativeEnum = 1,

            /// <summary>
            /// Enum AbsoluteEnum for absolute
            /// </summary>
            [EnumMember(Value = "absolute")]
            AbsoluteEnum = 2,
        }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = true)]
        public PositionEnum Position { get; set; }

        /// <summary>
        /// Gets or Sets OffsetTop
        /// </summary>
        [DataMember(Name = "offsetTop", EmitDefaultValue = false)]
        public string OffsetTop { get; set; }

        /// <summary>
        /// Gets or Sets OffsetBottom
        /// </summary>
        [DataMember(Name = "offsetBottom", EmitDefaultValue = false)]
        public string OffsetBottom { get; set; }

        /// <summary>
        /// Gets or Sets OffsetStart
        /// </summary>
        [DataMember(Name = "offsetStart", EmitDefaultValue = false)]
        public string OffsetStart { get; set; }

        /// <summary>
        /// Gets or Sets OffsetEnd
        /// </summary>
        [DataMember(Name = "offsetEnd", EmitDefaultValue = false)]
        public string OffsetEnd { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>

        public enum HeightEnum
        {
            /// <summary>
            /// Enum MdEnum for md
            /// </summary>
            [EnumMember(Value = "md")]
            MdEnum = 1,

            /// <summary>
            /// Enum SmEnum for sm
            /// </summary>
            [EnumMember(Value = "sm")]
            SmEnum = 2,
        }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", EmitDefaultValue = true)]
        public HeightEnum Height { get; set; }

        /// <summary>
        /// Gets or Sets AdjustMode
        /// </summary>

        public enum AdjustModeEnum
        {
            /// <summary>
            /// Enum ShrinkToFitEnum for shrink-to-fit
            /// </summary>
            [EnumMember(Value = "shrink-to-fit")]
            ShrinkToFitEnum = 1,
        }

        /// <summary>
        /// Gets or Sets AdjustMode
        /// </summary>
        [DataMember(Name = "adjustMode", EmitDefaultValue = true)]
        public AdjustModeEnum AdjustMode { get; set; }

        /// <summary>
        /// Gets or Sets Scaling
        /// </summary>
        [DataMember(Name = "scaling", EmitDefaultValue = true)]
        public bool Scaling { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FlexButton {\n");
            sb.Append("  Flex: ").Append(Flex).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Style: ").Append(Style).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Gravity: ").Append(Gravity).Append("\n");
            sb.Append("  Margin: ").Append(Margin).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  OffsetTop: ").Append(OffsetTop).Append("\n");
            sb.Append("  OffsetBottom: ").Append(OffsetBottom).Append("\n");
            sb.Append("  OffsetStart: ").Append(OffsetStart).Append("\n");
            sb.Append("  OffsetEnd: ").Append(OffsetEnd).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  AdjustMode: ").Append(AdjustMode).Append("\n");
            sb.Append("  Scaling: ").Append(Scaling).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions { WriteIndented = true };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((FlexButton)obj);
        }

        /// <summary>
        /// Returns true if FlexButton instances are equal
        /// </summary>
        /// <param name="other">Instance of FlexButton to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlexButton other)
        {
            if (other is null)
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Flex == other.Flex || Flex.Equals(other.Flex))
                && (Color == other.Color || Color != null && Color.Equals(other.Color))
                && (Style == other.Style || Style.Equals(other.Style))
                && (Action == other.Action || Action != null && Action.Equals(other.Action))
                && (Gravity == other.Gravity || Gravity.Equals(other.Gravity))
                && (Margin == other.Margin || Margin != null && Margin.Equals(other.Margin))
                && (Position == other.Position || Position.Equals(other.Position))
                && (
                    OffsetTop == other.OffsetTop
                    || OffsetTop != null && OffsetTop.Equals(other.OffsetTop)
                )
                && (
                    OffsetBottom == other.OffsetBottom
                    || OffsetBottom != null && OffsetBottom.Equals(other.OffsetBottom)
                )
                && (
                    OffsetStart == other.OffsetStart
                    || OffsetStart != null && OffsetStart.Equals(other.OffsetStart)
                )
                && (
                    OffsetEnd == other.OffsetEnd
                    || OffsetEnd != null && OffsetEnd.Equals(other.OffsetEnd)
                )
                && (Height == other.Height || Height.Equals(other.Height))
                && (AdjustMode == other.AdjustMode || AdjustMode.Equals(other.AdjustMode))
                && (Scaling == other.Scaling || Scaling.Equals(other.Scaling));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + Flex.GetHashCode();
                if (Color != null)
                    hashCode = hashCode * 59 + Color.GetHashCode();

                hashCode = hashCode * 59 + Style.GetHashCode();
                if (Action != null)
                    hashCode = hashCode * 59 + Action.GetHashCode();

                hashCode = hashCode * 59 + Gravity.GetHashCode();
                if (Margin != null)
                    hashCode = hashCode * 59 + Margin.GetHashCode();

                hashCode = hashCode * 59 + Position.GetHashCode();
                if (OffsetTop != null)
                    hashCode = hashCode * 59 + OffsetTop.GetHashCode();
                if (OffsetBottom != null)
                    hashCode = hashCode * 59 + OffsetBottom.GetHashCode();
                if (OffsetStart != null)
                    hashCode = hashCode * 59 + OffsetStart.GetHashCode();
                if (OffsetEnd != null)
                    hashCode = hashCode * 59 + OffsetEnd.GetHashCode();

                hashCode = hashCode * 59 + Height.GetHashCode();

                hashCode = hashCode * 59 + AdjustMode.GetHashCode();

                hashCode = hashCode * 59 + Scaling.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(FlexButton left, FlexButton right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FlexButton left, FlexButton right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
