/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{ 
    /// <summary>
    /// List of bots to which the module is attached
    /// </summary>
    [DataContract]
    public partial class GetModulesResponse : IEquatable<GetModulesResponse>
    {
        /// <summary>
        /// Array of Bot list Item objects representing basic information about the bot.
        /// </summary>
        /// <value>Array of Bot list Item objects representing basic information about the bot.</value>
        [Required]
        [DataMember(Name="bots", EmitDefaultValue=false)]
        public List<ModuleBot> Bots { get; set; }

        /// <summary>
        /// Continuation token. Used to get the next array of basic bot information. This property is only returned if there are more unreturned results. 
        /// </summary>
        /// <value>Continuation token. Used to get the next array of basic bot information. This property is only returned if there are more unreturned results. </value>
        [DataMember(Name="next", EmitDefaultValue=false)]
        public string Next { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetModulesResponse {\n");
            sb.Append("  Bots: ").Append(Bots).Append("\n");
            sb.Append("  Next: ").Append(Next).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetModulesResponse)obj);
        }

        /// <summary>
        /// Returns true if GetModulesResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetModulesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetModulesResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Bots == other.Bots ||
                    Bots != null &&
                    other.Bots != null &&
                    Bots.SequenceEqual(other.Bots)
                ) && 
                (
                    Next == other.Next ||
                    Next != null &&
                    Next.Equals(other.Next)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Bots != null)
                    hashCode = hashCode * 59 + Bots.GetHashCode();
                    if (Next != null)
                    hashCode = hashCode * 59 + Next.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GetModulesResponse left, GetModulesResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetModulesResponse left, GetModulesResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
