/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{ 
    /// <summary>
    /// Limit of the Narrowcast
    /// </summary>
    [DataContract]
    public partial class Limit : IEquatable<Limit>
    {
        /// <summary>
        /// The maximum number of narrowcast messages to send. Use this parameter to limit the number of narrowcast messages sent. The recipients will be chosen at random. 
        /// </summary>
        /// <value>The maximum number of narrowcast messages to send. Use this parameter to limit the number of narrowcast messages sent. The recipients will be chosen at random. </value>
        [DataMember(Name="max", EmitDefaultValue=true)]
        public int Max { get; set; }

        /// <summary>
        /// If true, the message will be sent within the maximum number of deliverable messages. The default value is &#x60;false&#x60;.  Targets will be selected at random. 
        /// </summary>
        /// <value>If true, the message will be sent within the maximum number of deliverable messages. The default value is &#x60;false&#x60;.  Targets will be selected at random. </value>
        [DataMember(Name="upToRemainingQuota", EmitDefaultValue=true)]
        public bool UpToRemainingQuota { get; set; } = false;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Limit {\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("  UpToRemainingQuota: ").Append(UpToRemainingQuota).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Limit)obj);
        }

        /// <summary>
        /// Returns true if Limit instances are equal
        /// </summary>
        /// <param name="other">Instance of Limit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Limit other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Max == other.Max ||
                    
                    Max.Equals(other.Max)
                ) && 
                (
                    UpToRemainingQuota == other.UpToRemainingQuota ||
                    
                    UpToRemainingQuota.Equals(other.UpToRemainingQuota)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Max.GetHashCode();
                    
                    hashCode = hashCode * 59 + UpToRemainingQuota.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Limit left, Limit right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Limit left, Limit right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
