/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// An object representing a mention substitution.
    /// </summary>
    [DataContract]
    public partial class MentionSubstitutionObject
        : SubstitutionObject,
            IEquatable<MentionSubstitutionObject>
    {
        /// <summary>
        /// Gets or Sets Mentionee
        /// </summary>
        [Required]
        [DataMember(Name = "mentionee", EmitDefaultValue = false)]
        public MentionTarget Mentionee { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MentionSubstitutionObject {\n");
            sb.Append("  Mentionee: ").Append(Mentionee).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public new string ToJson()
        {
            var options = new JsonSerializerOptions { WriteIndented = true };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((MentionSubstitutionObject)obj);
        }

        /// <summary>
        /// Returns true if MentionSubstitutionObject instances are equal
        /// </summary>
        /// <param name="other">Instance of MentionSubstitutionObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MentionSubstitutionObject other)
        {
            if (other is null)
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (
                Mentionee == other.Mentionee
                || Mentionee != null && Mentionee.Equals(other.Mentionee)
            );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Mentionee != null)
                    hashCode = hashCode * 59 + Mentionee.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(
            MentionSubstitutionObject left,
            MentionSubstitutionObject right
        )
        {
            return Equals(left, right);
        }

        public static bool operator !=(
            MentionSubstitutionObject left,
            MentionSubstitutionObject right
        )
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
