/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using JsonSubTypes;
using Liny.Core.Converters;
using Swashbuckle.AspNetCore.Annotations;

namespace Liny.Core.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    [SwaggerDiscriminator("Type")]
    [JsonSubtypes.KnownSubType(typeof(AudioMessageContent), "audio")]
    [SwaggerSubType(typeof(AudioMessageContent), DiscriminatorValue = "audio")]
    [JsonSubtypes.KnownSubType(typeof(FileMessageContent), "file")]
    [SwaggerSubType(typeof(FileMessageContent), DiscriminatorValue = "file")]
    [JsonSubtypes.KnownSubType(typeof(ImageMessageContent), "image")]
    [SwaggerSubType(typeof(ImageMessageContent), DiscriminatorValue = "image")]
    [JsonSubtypes.KnownSubType(typeof(LocationMessageContent), "location")]
    [SwaggerSubType(typeof(LocationMessageContent), DiscriminatorValue = "location")]
    [JsonSubtypes.KnownSubType(typeof(StickerMessageContent), "sticker")]
    [SwaggerSubType(typeof(StickerMessageContent), DiscriminatorValue = "sticker")]
    [JsonSubtypes.KnownSubType(typeof(TextMessageContent), "text")]
    [SwaggerSubType(typeof(TextMessageContent), DiscriminatorValue = "text")]
    [JsonSubtypes.KnownSubType(typeof(VideoMessageContent), "video")]
    [SwaggerSubType(typeof(VideoMessageContent), DiscriminatorValue = "video")]
    public partial class MessageContent : IEquatable<MessageContent>
    {
        /// <summary>
        /// Type
        /// </summary>
        /// <value>Type</value>
        [Required]
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Message ID
        /// </summary>
        /// <value>Message ID</value>
        [Required]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessageContent {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions { WriteIndented = true };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((MessageContent)obj);
        }

        /// <summary>
        /// Returns true if MessageContent instances are equal
        /// </summary>
        /// <param name="other">Instance of MessageContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessageContent other)
        {
            if (other is null)
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Type == other.Type || Type != null && Type.Equals(other.Type))
                && (Id == other.Id || Id != null && Id.Equals(other.Id));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(MessageContent left, MessageContent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MessageContent left, MessageContent right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
