/*
 * Merged API
 *
 * Merged OpenAPI specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Liny.Core.Converters;

namespace Liny.Core.Models
{
    /// <summary>
    /// One of the following values to indicate whether a target limit is set or not.
    /// </summary>
    /// <value>One of the following values to indicate whether a target limit is set or not.</value>

    public enum QuotaType
    {
        /// <summary>
        /// Enum NoneEnum for none
        /// </summary>
        [EnumMember(Value = "none")]
        NoneEnum = 1,

        /// <summary>
        /// Enum LimitedEnum for limited
        /// </summary>
        [EnumMember(Value = "limited")]
        LimitedEnum = 2,
    }
}
